---
apiVersion: v1
kind: Service
metadata:
  name: bdapi-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  bdapi-auth_mapping
      prefix: /auth/
      rewrite: /auth/
      service: bdapi-auth
spec:
  selector:
    app: bdapi-auth
  ports:
  - port: 80
    name: http-bdapi-auth
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdapi-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bdapi-auth
    spec:
      containers:
      - name: bdapi-auth
        image: buildarium/bdapi-auth:latest
        imagePullPolicy: "Always"
        env:
        - name: ENV
          value: "prod"
        - name: POSTGRESUSER
          valueFrom:
            secretKeyRef:
              name: bdapi-secret
              key: postgresuser
        - name: POSTGRESPASS
          valueFrom:
            secretKeyRef:
              name: bdapi-secret
              key: postgrespass
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: bdapi-secret
              key: sendgridapikey
        ports:
        - name: http-api
          containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
        # resources:
        #   limits:
        #     cpu: "0.1"
        #     memory: 100Mi
